version: '3.9'

services:
  ui:
    container_name: myfirstcontainer
    build:
      context: .
      dockerfile: Dockerfile
    image: myfirstimage
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development